/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//1. Enable all configurable exceptions like usage fault, mem manage fault, and bus fault
	uint32_t *pSHCSR = (uint32_t *)0xE000ED24;	//Address of System handler control and state register
	*pSHCSR |= (1<<16); //Mem manage
	*pSHCSR |= (1<<17); //bus fault
	*pSHCSR |= (1<<18); //usage fault

	//3. lets force the processor to execute some undefined instruction.
	uint32_t *pSRAM = (uint32_t *)0x20010000;	//Pointer to some address in SRAM Region
	*pSRAM = 0xFFFFFFFF;						//Modifying data at the location at which the pointer is pointing at.

	void(*some_address) (void);					//Creating a function pointer.

	some_address = (void*)((uint32_t *)pSRAM + 1);	//Initialize this function pointer to this SRAM location.

	some_address();								//Dereference this function pointer.
	//4. Analyze the fault
    /* Loop forever */
	for(;;);
}

//2. Implement the fault handlers

void HardFault_Handler(void)
{
	printf("[Hardfault Exception occurred]");
	while(1);
}

void MemManage_Handler(void)
{
	printf("[MemMange Exception occurred]");
	while(1);
}

void BusFault_Handler(void)
{
	printf("[BusFault Exception occurred]");
	while(1);
}

__attribute__((naked)) void UsageFault_Handler(void)	//Caller
{
	/*
	 * Here we extracted the value of MSP which happens to be base address of the stack frame.(thread mode code)
	 * which got saved during the exception entry from thread mode to handler mode.
	 */
	__asm volatile("MRS r0,MSP");
	__asm volatile("B UsageFault_Handler_c");
}

/*
 * Now according to the ARM Procedure Call standard document.
 * General register 'r0' becomes the argument 1 [i.e. pBaseStackFrame] for the callee.
 */

void UsageFault_Handler(uint32_t *pBaseStackFrame)	//Callee
{
	uint32_t *pMSP = (uint32_t*)msp_value;
	uint32_t *pUFSR = (uint32_t *)0xE000ED2A;	//Address of usage fault status register.
	printf("[Usage Exception occurred]");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF);	//UFSR is a 16 bit register.

	//Printing stack
	printf("MSP = %p\n", pBaseStackFrame);
	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
	printf("Value of xPSR = %lx\n", pBaseStackFrame[7]);
	while(1);
}
