/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*NOTE: This code works for only STM32F407 Discovery Board!*/

// Operational Modes and Access Levels

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*This function executes in Thread mode of the processor */
void generate_interrupt(){
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//Enable IRQ3 interrupt
	*pISER0 |= (1<<3);

	//Generate an Interrupt from software from IRQ3
	*pSTIR = (3 & 0x1FF);
}

void change_access_level_unpriv(void){
	/*Read, Modify and Write
	 * Read control reg, modify control register and then write to control reg.
	 * so special reg and general purpose registers. so MSR and MRS
	*/
	//read
	__asm volatile("MRS R0,CONTROL");	//Using MRS, Perform Read operation and Access the Control register and read it in R0 Register.
	//Modify
	__asm volatile("ORR R0,R0,#0x01");	//Using logical OR, i will set 1 bit in read control register, saved in R0
	//Write
	__asm volatile("MSR CONTROL,R0");	//Using MSR, Perform Write operation to special register of the processor i.e. Control Register.

	/*
	 * Now the processor is in Unprivileged Mode, hence it cannot access some privileged address. if it tries to access,
	 * processor fault exception will occur.*/
}

/*This function executes in Thread mode of the processor */
int main(void)
{
	printf("In Thread Mode: before Interrupt\n");

	generate_interrupt();

	printf("In thread mode: After Interrupt\n");
    /* Loop forever */
	for(;;);
}

/* This function (ISR) executes in Handler mode of the Processor */
void RTC_WKUP_IRQHANDLER(void){
	printf("In Handler mode: ISR\n");
}

void HardFault_Handler(void){
	printf("Hard Fault detected\n");
}
