/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER3	29
#define IRQNO_I2C1		31

uint32_t *pNVIC_IPRBase = (uint32_t*) 0xE000E400;		//Interrupt Priority Register
uint32_t *pNVIC_ISERBase = (uint32_t*) 0xE000E100;	//Interrupt Set-Enable Register
uint32_t *pNVIC_ISPRBase = (uint32_t*) 0XE000E200;	//Interrupt Set Priority Register

void configure_priority_for_irqs(uint8_t irq_no, uint8_t priority_value){
	//NVIC - Priority register, Interrupt pending register and interrupt set-enable register
	//1. Find out IPRx
	uint8_t iprx = irq_no/4;
	uint32_t *ipr = pNVIC_IPRBase + iprx;	//IPR Base register + iprx -> to get the address of IPR related to our IRQ_No

	//2.Find position in IPRx
	uint8_t pos = (irq_no % 4) * 8;		//to get the position in IPRx register

	//3. Configure the priority
	*ipr &= ~(0xff << pos);	//Clear the IPR Register
	*ipr |= (priority_value << pos);	//Set the IPR Register
}

int main(void)
{
	//1. Lets configure the priority for the peripherals
	configure_priority_for_irqs(IRQNO_TIMER3, 0x70);

	configure_priority_for_irqs(IRQNO_I2C1, 0x80);

	//2. Set the interrupt pending bit in the NVIC PR
	*pNVIC_ISPRBase |= (1 << IRQNO_TIMER3);

	//3. Enable the IRQ in NVIC ISER
	*pNVIC_ISERBase |= (1 << IRQNO_TIMER3);
	*pNVIC_ISERBase |= (1 << IRQNO_I2C1);

    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void){
	printf("[TIM2_IRQHandler]\n");
}

void I2C1_EV_IRQHandler(void)
{
	printf(":[I2C1_EV_IRQHandler]\n");
}
