/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Write a program to execute an SVC Instruction from thread mode, implement the SVC Handler to print the SVC number used.
 * Also, increment the SVC Number by 4 and return it to the thread mode code and print it.
 *
 * Hints:
 * 1) Write a main() function where you should execute the SVC Instruction with an argument. ex SVC #0x5
 * 2) Implement the SVC Handler
 * 3) In the SVC Handler extract the SVC number and print it using printf
 * 4) Increment the SVC number by 4 and return it to the thread mode.
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SVC_Handler_c(uint32_t *pBaseOfStackFrame);

int main(void)
{
	__asm volatile("SVC #8");

	/*
	//4. Here the Processor does not create a variable in the stack but in on one of the Processor registers ex. r0
	register uint32_t data __asm("R0");
	*/

	uint32_t data;

	__asm volatile("MOV %0, R0": "=r"(data) ::);

	printf("Data: %ld\n", data);
    /* Loop forever */
	for(;;);
}

__attribute__((naked)) void SVC_Handler(uint32_t *pBaseOfStackFrame){
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame){
	printf("[In SVC Handler]\n");
	/*To Get the SVC Number*/
	//1. Get the value of MSP
	uint8_t *pReturn_addr = (uint8_t *)pBaseOfStackFrame[6];

	//2. Decrement the return address by 2 to point to opcode of the SVC Instruction in the program memory
	pReturn_addr--;
	pReturn_addr--;

	//3. Extract the SV Number i.e. least significant byte of the Opcode.
	uint8_t svc_number = *pReturn_addr;
	printf("SVC Number is: %d\n", svc_number);

	svc_number += 4;
	pBaseOfStackFrame[0] = svc_number;
}


