/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	//Creating a pointer variable of RCC AHB1ENR Register with typedef structure.
	RCC_AHB1ENR_t volatile *const pClkCtrlReg = (RCC_AHB1ENR_t*)0x40023830;;

	//Creating a pointer variable of GPIOA MODE Register with typedef structure.
	GPIOx_MODER_t volatile *const pGpioAModeReg = (GPIOx_MODER_t*)0x40020000;

	//Creating a pointer variable of GPIOx Output Data Register with typedef structure.
	GPIOx_ODR_t volatile *const pGpioAOutReg = (GPIOx_ODR_t*)0x40020014;

	pClkCtrlReg->GPIOA_EN = 1;

	pGpioAModeReg->MODER5 = 1;	//1 --> 01 in Hex format, selected as Output mode

	//pGpioAOutReg->ODR5 = 1;

	while (1){
		pGpioAOutReg->ODR5 = 1;
		for(uint32_t i = 0; i < 300000; i++);
		pGpioAOutReg->ODR5 = 0;
		for(uint32_t i = 0; i < 300000; i++);
	}
}
