/*<
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER2	28
#define IRQNO_I2C1		31

uint8_t *pNVIC_IPRBase = (uint8_t*) 0xE000E400;		//Interrupt Priority Register
uint8_t *pNVIC_ISERBase = (uint8_t*) 0xE000E100;	//Interrupt Set-Enable Register
uint8_t *pNVIC_ISPRBase = (uint8_t*) 0XE000E200;	//Interrupt Set Priority Register

void configure_priority_for_irqs(uint8_t irq_no, uint8_t priority_value){
	//NVIC - Priority register, Interrupt pending register and interrupt set-enable register
	//1. Find out IPRx
	uint8_t iprx = irq_no/4;
	uint32_t *ipr = pNVIC_IPRBase + iprx;	//IPR Base register + iprx -> to get the address of IPR related to our IRQ_No

	//2.Find position in IPRx
	uint8_t pos = (irq_no % 4) * 8;		//to get the position in IPRx register

	//3. Configure the priority
	*ipr &= ~(0xff << pos);	//Clear the IPR Register
	*ipr |= (priority_value << pos);	//Set the IPR Register
}

int main(void)
{
	//1. Lets configure the priority for the peripherals
	configure_priority_for_irqs(IRQNO_TIMER2, 0x80);
	configure_priority_for_irqs(IRQNO_I2C1, 0x70);

	//2. Set the interrupt pending bit in the NVIC PR //ISP - Interrupt set pending register
	*pNVIC_ISPBase |= (1 << IRQNO_TIMER2);

	//3. Enable the IRQs in NVIC ISER
	*pNVIC_ISERBase |= (1 << IRQNO_TIMER2);
	*pNVIC_ISERBase |= (1 << IRQNO_I2C1);

    /* Loop forever */
	for(;;);
}

//ISR's

void TIM2_IRQHandler(void){
	printf("[TIM2_IRQHandler]");
	*pNVIC_ISPBase |= (1 << IRQNO_I2C1);	//set pending bit for I2C1
	/*
	 * ISR of I2C will not be executed as the Priority of I2C peripheral is not higher than TIM2 (the current interrupt),
	 * so it will be in pending state
	 * so for I2C Interrupt to occur, we can increase the priority of I2C1 peripheral.
	 * so after making the I2C1 Interrupt higher, you can get an interrupt. so here this is called nested interrupt.
	 * so here, lowert priority interrupt handler was running, higher interrupt activated, the lower priority interrupt got preempted
	 * and processor started executing the higher priority handler. this is called interrupt nesting.
	 */
	while(1);
}

void I2C1_EV_IRQHandler(void){
	printf("[I2C1_EV_IRQHandler]");
}


