/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Address of Clock control Register RCCAHB1ENR
	uint32_t volatile *const pClkCtrlReg = (uint32_t*)0x40023830;
	//Address of GPIO Mode Register
	uint32_t volatile *const pPortAModeReg = (uint32_t*)0x40020000;
	//Address of GPIOC Mode Register
	uint32_t volatile *const pPortCModeReg = (uint32_t*)0x40020800;
	//Address of GPIOA Output Data Register
	uint32_t volatile *const pPortAOutReg = (uint32_t*)0x40020014;
	//Address of GPIOC Output Data Register
	//uint32_t volatile *const pPortCOutReg = (uint32_t*)0x40020814;
	//Address of GPIOC Input Register
	uint32_t const volatile *const pPortCInReg = (uint32_t*)0x40020810;  //Input data register, and programmer should'nt write anything

	/*
	 * Enable the clock for GPIOA & C Peripheral in the AHB i.e bit 0
	*/
	//*pClkCtrlReg |= 0x05;
	*pClkCtrlReg |= (1<<2) | (1<<0);

	//Port A; PA5
	*pPortAModeReg &= ~(3<<10);//~(1<<10) | ~(1<<11);
	*pPortAModeReg |= (1<<10);

	//Configure PC13 as Input mode
	//Port C, PC13
	*pPortCModeReg &= (3<<26);
	*pPortCModeReg |= ~(3<<26);

//Method 1
//	while (1){
//		//Read the GPIO C Input Data Register
//		uint32_t temp = *pPortCInReg;
//		if((temp & 0x2000) == 0x2000){
//			*pPortAOutReg |= (1<<5);//LED On;
//		}
//		else{
//			*pPortAOutReg &= ~(1<<5);//LED Off;
//		}
//	}
//Method 2
	while (1){
		//Read the GPIO C Input Data Register
		volatile uint32_t temp = ((*pPortCInReg >> 13));
		if(temp == 0){
			*pPortAOutReg |= (1<<5);//LED On;
		}
		else{
			*pPortAOutReg &= ~(1<<5);//LED Off;
		}
	}
}
