/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * 1. Initiate Debug Session and look into Registers section and look into SP, MSP, and PSP Values initialized.
 * 	  Also look into Startupfile - vector table (_estack) and .ld file in Debug folder.
 * 2. Exercise: Change SP to PSP for thread mode.
 */
#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SRAM_START			0x20000000U
#define SRAM_SIZE			(128*1024)
#define SRAM_END			((SRAM_START) + (SRAM_SIZE))

#define STACK_START			SRAM_END
#define STACK_MSP_START		STACK_START
#define STACK_MSP_END		(STACK_MSP_START + 512)
#define STACK_PSP_START		STACK_MSP_END


int fun_add(int a, int b, int c, int d){
	return a+b+c+d;
}

__attribute__((naked)) void change_sp_to_psp(void)
{
	__asm volatile(".equ SRAM_END, (0x20000000 + (128*1024))");	//Get SRAM End value/Address
	__asm volatile(".equ PSP_START, (SRAM_END-512)");			//Load SRAM VALUE/address in PSP Start
	__asm volatile("LDR R0, =PSP_START");	//Load general register R0 and initialize a value for PSP
	__asm volatile("MSR PSP, R0");				//Load PSP into R0
	__asm volatile("MOV R0,#0X02");				//Change SPSEL bit in control reg, therefore move 0x02 in control reg, to change bit 1.
	__asm volatile("MSR CONTROL, R0");			//Move 0x02 stored in R0 to control register, to change SPSEL Bit in CONTROL Register.
	//Now return to main function, use written function
	__asm volatile("BX LR");					//Contents of LR will be copied to PC
}

void generate_exception(void){
	__asm volatile("SVC #0x2");
}

int main(void)
{
	change_sp_to_psp();
	int ret;
	ret = fun_add(1, 4, 5, 6);
	printf("Result: %d\n", ret);

	generate_exception();
    /* Loop forever */
	for(;;);
}

void SVC_Handler(void){
	printf(" in SVC_Handler\n");
}

