/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define DELAY_COUNT 300000UL

int main(void)
{
	//Creating a pointer variable of RCC AHB1ENR Register with typedef structure.
	RCC_AHB1ENR_t volatile *const pClkCtrlReg = ADDR_REG_AHB1ENR;

	//Creating a pointer variable of GPIOA MODE Register with typedef structure.
	GPIOx_MODER_t volatile *const pGpioAModeReg = ADDR_REG_GPIOA_MODE;

	//Creating a pointer variable of GPIOA Output Data Register with typedef structure.
	GPIOx_ODR_t volatile *const pGpioAOutReg = ADDR_REG_GPIOA_ODR;

	pClkCtrlReg->GPIOA_EN = RCC_ENABLE;

	pGpioAModeReg->MODER5 = GPIO_MODE_1;	//1 --> 01 in Hex format, selected as Output mode

	while (1){
		pGpioAOutReg->ODR5 = GPIO_HIGH;
		for(uint32_t i = 0; i < DELAY_COUNT; i++);
		pGpioAOutReg->ODR5 = GPIO_LOW;
		for(uint32_t i = 0; i < DELAY_COUNT; i++);
	}
}
