/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define TIM3_IRQ_No 29

int main(void)
{
	printf("Checking SWV Console working or not!\n");
	//1. Manually pend the pending bit for the Timer3 IRQ number in NVIC
	uint32_t *pISPR0 = (uint32_t*)0XE000E200;	//base address + 4
	*pISPR0 |= (1 << (TIM3_IRQ_No % 32));	//therefore (1 << 29) in ISPR0 Register.
	/*
	 * why 32? in Interrupt set pending register, we can set pending state for 32 IRQ's so 29 % 32 will give us 29, so in ISPR1, 4th bit.
	 * ISPR0 TO ISPR7, total of 8 registers to set 240 interrupts.
	*/
	//2. Enable the Timer3 IRQ Number in NVIC
	uint32_t *pISER0 = (uint32_t*)0xE000E100;
	*pISER0 |= (1 << (TIM3_IRQ_No % 32));	//therefore (1<<29)

    /* Loop forever */
	for(;;);
}

void TIM3_IRQHandler(void){
	printf("[TIM3_IRQHandler]\n");
}
