/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Under AF07
 * USART Tx - PA2
 * USART Rx - PA3
 */

#include "stm32f4xx.h"
#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//USART Clock
#define SYS_FREQ		16000000		//Default system frequency
//In clock tree, the system clock is taken and then it is divided by a value
#define APB1CLK			SYS_FREQ

#define UART_BAUDRATE	115200
#define CR1_TE			(1U<<3)
#define CR1_UE			(1<<13)
#define SR_TXE			(1U<<7)

#define GPIOAEN			(1U<<0)
#define USART2EN		(1U<<17)

static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphCLK, uint32_t BaudRate);
static uint16_t Compute_UART_div_bd(uint32_t PeriphCLK, uint32_t BaudRate);
void usart2_tx_init(void);
void uart2_write(int ch);
void uart_Wstring(char *message);

int main(void)
{
	usart2_tx_init();

    while(1){
    	//Send message
    	//uart2_write('Y');
    	uart_Wstring("[Hello, World!]\n\r");

    }
}

void usart2_tx_init(void)
{
	/***********Configure UART Tx GPIO Pin***********/	//PA2 -> UART_Tx pin
	/*Enable Clock access to UART Tx GPIO Pin*/
	RCC->AHB1ENR |= GPIOAEN;

	/*Set the UART Tx GPIO Pin to Alternate function mode*/
	//5,4 - 10
	GPIOA->MODER &= ~(1U<<4);
	GPIOA->MODER |= (1U<<5);

	/*Set the UART Tx GPIO Pin to alternate function type to UART_Tx (AF07)*/
	//AFRL [PA2] -> 11,10,9,8 -- 0111
	//AFR[0] - L ; [1] - h
	GPIOA->AFR[0] &= ~(1U<<11);
	GPIOA->AFR[0] |= (1U<<10);
	GPIOA->AFR[0] |= (1U<<9);
	GPIOA->AFR[0] |= (1U<<8);

	/***********Configure the USART Module***********/
	/*Enable Clock access to UART 2*/ //APB1
	RCC->APB1ENR |= USART2EN;

	/*Configure Baud rate*/
	uart_set_baudrate(USART2, APB1CLK, UART_BAUDRATE);

	/*Configure the transfer direction*/ //Enable the TX pin
	USART2->CR1 = CR1_TE;	//by not using OR(|), we set all bits 0 except bit 3. hence we get the default settings.
	//Therefore 1 start bit, 8 data bits and 2 stop bits. hardware flow control etc are all disabled.

	/*Enable the USART Module*/
	USART2->CR1 |= CR1_UE;	//We used OR Operator (|) To make sure not to set all the other bits to 0.
}

void uart_Wstring(char *message){
	for(int i = 0; message[i] != '\0'; i++){
		uart2_write(message[i]);
	}
}

void uart2_write(int ch){
	/*Make sure the transmit data register is empty*/
	while(!(USART2->SR & SR_TXE)){};

	/*Write the Data transmit register //Data register*/
	USART2->DR = (ch & 0xff);
}

static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphCLK, uint32_t BaudRate){
	USARTx->BRR = Compute_UART_div_bd(PeriphCLK, BaudRate);
}

static uint16_t Compute_UART_div_bd(uint32_t PeriphCLK, uint32_t BaudRate){
	return ((PeriphCLK + (BaudRate/2U))/BaudRate);
}



