/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
//Basic Example for inline assembly coding
#if 0
//Load in Register R1, then Specifying the register on which the memory address is based or directly specifying the Memory Address.
	__asm volatile("LDR R1,=#0x20001000");	// loading the Memory Address in R1
	__asm volatile("LDR R1,=#0x20001004");	// Loading the Memory Address in R2

	__asm volatile("LDR R0,[R1]");			//Load R1(source) in R0(Destination)
	__asm volatile("LDR R1,[R2]");			//Load R2)Source) in R2(Destination
	__asm volatile("ADD R0,R0,R1");			//Add R0 and R1, then store the result in R0 ????
	__asm volatile("STR R0,[R2]");			//Store R2 in R0
#endif

//Example 1: Move the content of 'C' variable to ARM Register R0. Using Input Operand example
	int val=50;
	__asm volatile("MOV R0,%0": :"r"(val));

//Example 2: Move the content of control register to C variable "control_reg"
	//The control Register is a special register of the ARM Core.
	//Instruction: MRS rd rs --> rd is destination register i.e register ; rs is source register i.e special register
	// MRS is used for read operation i.e to read from special register to store in register
	// MSR is used for write operation
	uint32_t control_reg;
	__asm volatile("MRS %0,CONTROL":"=r"(control_reg)::);

//Example 3: Copy the content of 'C' variable var1 and var2
	int var1 = 10, var2;
	__asm volatile("MOV %0,%1":"=r"(var2):"r"(var1));	//"=r" is write only and "r" is read only operations.

//Example 4: Copy the contents of a pointer into another variable
	int p1, *p2;
	p2 = (int*)0x20000008;
	__asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2)); //p1 = *p2



	/* Loop forever */
	for(;;);
}
