/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Address of Clock control Register RCCAHB1ENR
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	//Address of GPIO Mode Register
	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	//Address of GPIOC Mode Register
	uint32_t *pPortCModeReg = (uint32_t*)0x40020800;
	//Address of GPIOA Output Data Register
	uint32_t *ppPortAOutReg = (uint32_t*)0x40020014;
	//Address of GPIOC Output Data Register
	uint32_t *ppPortCOutReg = (uint32_t*)0x40020814;

	/*
	 * Enable the clock for GPIOA Peripheral in the AHB i.e bit 0
	*/
	//*pClkCtrlReg |= 0x05;
	*pClkCtrlReg |= (1<<2) | (1<<0);

	/*
	 * Configure the mode of the I/O pin as Output i.e GPIOA Mode Register {for PA5 - Moder5]
	 * 1. clear the bit positions at PA5 or Moder5
	 * 00 -> clearing using & operation
	 * 01 -> Setting using | operation   (bit 11,10 for Moder5, 01 as GP Output)
	 * Create a mask value where except Moder5 all are 1 i.e 0xFFFFF3FF (only Moder5 is 0 i.e bit 11,10]
	 * Mask for setting a value in Moder5 i.e 0x00000800 -> 11,10,9,8 -> 0,1,0,0 i.e 8
	 *
	 * 2. Clear Moder5 bit positions and set Moder5 bit positions i.e 11,10 -> 0,1 ; for GP output mode selection
	*/
	//Port A; PA5
//	*pPortAModeReg &= 0xFFFFF3FF; //Clear Moder5
//	*pPortAModeReg |= 0x00000800; //Set Moder5
	*pPortAModeReg &= ~(3<<10); //~(1<<10) | ~(1<<11);
	*pPortAModeReg |= (1<<10);

	//Port C, PC9
	*pPortCModeReg &= ~(3<<18);//0xFFF7FFFF; //Clear Moder9
	*pPortCModeReg |= (1<<18); //0x00040000; //Set Moder9

	/*
	 * 3. Set the 5th bit (PA5) of the output data register to make I/O pin-5 as HIGH.
	 * Set values using OR operation Clear values by AND operations.
	 * Set mask for PA5 -> 0x0020 [15:0]
	*/
	//Port A, PA5
	*ppPortAOutReg |= (1<<5);//0x0020;

	//Port C, PC9
	*ppPortCOutReg |= (1<<9);//0x0200;

	while (1);
}
