/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for(uint32_t d = 0; d < 300000; d++);
}

int main(void)
{
	//Creating a pointer variable of RCC AHB1ENR Register with typedef structure.
	RCC_AHB1ENR_t volatile *const pClkCtrlReg = (RCC_AHB1ENR_t*)0x40023830;

	//Creating a pointer variable of GPIOC MODE Register with typedef structure.
	GPIOx_MODER_t volatile *const pGpioCModeReg = (GPIOx_MODER_t*)0x40020800;

	//Creating a pointer variable of GPIOC Pull-Up/Pull-Down Register with typedef structure.
	GPIOx_PUPDR_t volatile *const pGpioCPUPDRReg = (GPIOx_PUPDR_t*)0x4002080C;

	//Creating a pointer variable of GPIOC Input Data Register with typedef structure.
	GPIOx_IDR_t const volatile *const pGpioCInReg = (GPIOx_IDR_t*)0x40020810; //Input data register, and programmer should'nt write anything

	//Creating a pointer variable of GPIOx Output Data Register with typedef structure.
	GPIOx_ODR_t volatile *const pGpioCOutReg = (GPIOx_ODR_t*)0x40020814;

	//Enable RCC Clock for GPIO C Peripheral
	pClkCtrlReg->GPIOC_EN = 1;

	//Set GPIO C peripheral pins mode
	pGpioCModeReg->MODER10 = 0;	//PC10 i.e. C1 set as Input Mode
	pGpioCModeReg->MODER11 = 0;	//PC11 i.e. C2 set as Input Mode
	pGpioCModeReg->MODER12 = 0;	//PC12 i.e. C3 set as Input Mode

	pGpioCModeReg->MODER5 = 1;		//PC5 i.e R1 set as Output Mode
	pGpioCModeReg->MODER6 = 1;		//PC6 i.e R2 set as Output Mode
	pGpioCModeReg->MODER8 = 1;		//PC8 i.e R3 set as Output Mode
	pGpioCModeReg->MODER9 = 1;		//PC9 i.e R4 set as Output Mode

	//Set Pull-up configuration on Input pins 10,11,12
	pGpioCPUPDRReg->PUPDR10 = 1;	//Pull up configuration on PC10
	pGpioCPUPDRReg->PUPDR11 = 1;	//Pull up configuration on PC11
	pGpioCPUPDRReg->PUPDR12 = 1;	//Pull up configuration on PC12

	//Making R1,R2,R3,R4 pins HIGH
	pGpioCOutReg->ODR5 = 1;
	pGpioCOutReg->ODR6 = 1;
	pGpioCOutReg->ODR8 = 1;
	pGpioCOutReg->ODR9 = 1;

	while(1){
		//Reading Row 1  -- R1 = 0; R2 = 1; R3 = 1; R4 = 1
		pGpioCOutReg->ODR5 = 0;
		if(pGpioCInReg->IDR10 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'1\'\n");
		}
		if(pGpioCInReg->IDR11 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'2\'\n");
		}
		if(pGpioCInReg->IDR12 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'3\'\n");
		}

		//Reading Row 2	 -- R1 = 1; R2 = 0; R3 = 1; R4 = 1
		pGpioCOutReg->ODR5 = 1;
		pGpioCOutReg->ODR6 = 0;
		if(pGpioCInReg->IDR10 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'4\'\n");
		}
		if(pGpioCInReg->IDR11 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'5\'\n");
		}
		if(pGpioCInReg->IDR12 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'6\'\n");
		}

		//Reading Row 3  -- R1 = 1; R2 = 1; R3 = 0; R4 = 1
		pGpioCOutReg->ODR6 = 1;
		pGpioCOutReg->ODR8 = 0;
		if(pGpioCInReg->IDR10 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'7\'\n");
		}
		if(pGpioCInReg->IDR11 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'8\'\n");
		}
		if(pGpioCInReg->IDR12 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'9\'\n");
		}

		//Reading Row 3  -- R1 = 1; R2 = 1; R3 = 1; R4 = 0
		pGpioCOutReg->ODR8 = 1;
		pGpioCOutReg->ODR9 = 0;
		if(pGpioCInReg->IDR10 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'*\'\n");
		}
		if(pGpioCInReg->IDR11 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'0\'\n");
		}
		if(pGpioCInReg->IDR12 == 0){
			for(int i=0; i < 400000; i++);	//for Key debouncing
			printf("Key is \'#\'\n");
		}
		pGpioCOutReg->ODR9 = 1;
	}
}
