/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//UL - Unsigned long
// Typecast it to a volatile int pointer and then dereference the pointer

#define PERIPH_BASE			(0x40000000UL)
#define AHB1PERIPH_OFFSET	(0x20000000UL)
#define AHB1PERIPH_BASE		(PERIPH_BASE + AHB1PERIPH_OFFSET)

#define GPIOA_OFFSET		(0x0000U)
#define GPIOA_BASE			(AHB1PERIPH_BASE + GPIOA_OFFSET)

#define RCC_OFFSET			(0x3800)
#define RCC_BASE			(AHB1PERIPH_BASE + RCC_OFFSET)

#define RCC_AHB1ENR_OFFSET	(0x30UL)
#define RCC_AHB1ENR			(*(volatile unsigned int *)(RCC_BASE + RCC_AHB1ENR_OFFSET))
#define GPIOAEN				(1U<<0)	//0b 0000 0000 0000 0000 0000 0000 0000 0001

#define GPIOA_MODER_OFFSET	(0x00UL)
#define GPIOA_MODER			(*(volatile unsigned int *)(GPIOA_BASE + GPIOA_MODER_OFFSET))

#define GPIOA_ODR_OFFSET	(0x14UL)
#define GPIOA_ODR			(*(volatile unsigned int *)(GPIOA_BASE + GPIOA_ODR_OFFSET))

#define PIN5				(1U<<5)
#define LED_PIN				(PIN5)

int main(void)
{
	/* 1. Enable clock access to GPIOA */
	RCC_AHB1ENR |= GPIOAEN;

	/* 2. SET PA5 as Output pin */
	GPIOA_MODER |= (1U<<10);		//Set bit 10 as 1
	GPIOA_MODER &= ~(1U<<11);		//Set bit 11 as 0
	/*This makes sure that only bit 11 is set 0 (only bit 11 is modified during this operation)*/

	while(1){
		/*3. SET PA5 High*/
		//GPIOA_ODR |= LED_PIN;

		/*4. EXP2: Toggle PA5*/
		GPIOA_ODR ^= LED_PIN;
		for(int i=0; i<1000000; i++){}
	}
}
